name: .NET Build and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      run: dotnet test --no-restore --verbosity normal

    - name: Pack
      run: dotnet pack --configuration Release --no-build --output ./nupkg

    - name: Publish to NuGet
      if: github.event_name == 'push'
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_PACKAGE_TOKEN }}
      run: dotnet nuget push ./nupkg/*.nupkg --api-key $NUGET_PACKAGE_TOKEN --source https://api.nuget.org/v3/index.json
